Repository Coflnet/hypixel-react, pull requests merged in 2021-07, with the labels that each got.

#241 show autoscroll to everyone
  package-lock.json
  src/components/Flipper/Flipper.tsx
  src/components/Flipper/FlipperFilter/FlipperFilter.css
  src/components/Flipper/FlipperFilter/FlipperFilter.tsx
Labels: bug, enhancement, important

#244 fix filter
  src/components/Flipper/FlipperFilter/FlipperFilter.tsx
Labels: bug

#237 dynamic properties
  src/properties.js
  src/properties.json
  src/utils/PropertiesUtils.tsx
Labels: important

#278 FIX
  src/api/WebsocketHelper.tsx
Labels: breaking, bug

#304 graph bug fix
  src/components/PriceGraph/PriceGraph.tsx
Labels: breaking, bug

#307 highly improved tracking
  src/components/MainApp/MainApp.tsx
  src/routes.tsx
Labels: important

#308 track users who have already given consent before
  src/components/MainApp/MainApp.tsx
Labels: breaking, bug

#330 reload filters
  src/components/PriceGraph/PriceGraph.tsx
Labels: breaking, bug
