Repository Coflnet/hypixel-react, pull requests merged in 2021-08, with the labels that each got.

#348 remove apply from tests
  cypress/integration/filter.spec.ts
Labels: bug

#364 fix flipper styling
  src/components/Flipper/Flipper.css
  src/components/Flipper/Flipper.tsx
Labels: important

#367 new link
  src/components/Flipper/Flipper.tsx
  src/components/NavBar/NavBar.tsx
  src/pages/Feedback/Feedback.tsx
Labels: breaking, bug

#370 fix html
  src/components/Startpage/Startpage.tsx
Labels: bug, breaking

#374 fix filter styling
  src/components/FilterElement/FilterElement.css
  src/components/FilterElement/FilterElement.tsx
  src/components/ItemFilter/ItemFilter.css
  src/components/ItemFilter/ItemFilter.tsx
Labels: bug, breaking

#440 fix blacklist search
  src/components/Search/Search.tsx
Labels: bug, breaking
