Repository Coflnet/hypixel-react, pull requests merged in 2021-06, with the labels that each got.

#136 fixes
  public/preScript.js
  src/components/AuctionDetails/AuctionDetails.tsx
  src/components/Flipper/Flipper.tsx
  src/components/GoogleSignIn/GoogleSignIn.tsx
  src/components/Premium/Premium.tsx
  src/utils/GoogleUtils.tsx
Labels: breaking, bug

#146 links open in new tab
  src/components/Flipper/Flipper.tsx
Labels: enhancement

#145 Improved hamburger icon
  src/components/NavBar/NavBar.css
  src/pages/About/About.css
  src/pages/Flipper/Flipper.css
  src/pages/PaymentCancel/PaymentCancel.css
  src/pages/PaymentSuccess/PaymentSuccess.css
  src/pages/Premium/Premium.css
  src/pages/Subscriptions/Subscriptions.css
Labels: enhancement

#167 fix
  src/components/Flipper/Flipper.tsx
  src/react-app-env.d.ts
Labels: breaking, bug

#176 both filter now work
  cypress/integration/flipperFilter.spec.js
  src/components/AuctionList/AuctionList.tsx
  src/components/BidList/BidList.tsx
  src/components/Flipper/Flipper.css
  src/components/Flipper/Flipper.tsx
  src/components/Flipper/FlipperFilter/FlipperFilter.tsx
Labels: breaking, bug

#123 Filter Update
  .gitignore
  craco.config.js
  cypress/integration/filter.spec.ts
  cypress/integration/home.spec.js
  cypress/integration/search.spec.js
  cypress/tsconfig.json
  package-lock.json
  package.json
  public/serviceWorker.js
  src/api/ApiHelper.tsx
  src/api/ApiTypes.d.tsx
  src/api/HttpHelper.tsx
  src/components/FilterElement/FilterElement.css
  src/components/FilterElement/FilterElement.tsx
  src/components/ItemFilter/ItemFilter.css
  src/components/ItemFilter/ItemFilter.tsx
  src/components/ItemPriceRange/ItemPriceRange.tsx
  src/components/MainApp/MainApp.tsx
  src/components/PriceGraph/PriceGraph.tsx
  src/components/RecentAuctions/RecentAuctions.tsx
  src/react-app-env.d.ts
  src/utils/Formatter.tsx
  src/utils/Parser/APIResponseParser.tsx
  src/utils/Parser/URLParser.tsx
Labels: enhancement, important

#201 fixes
  src/components/Flipper/Flipper.tsx
  src/pages/About/About.tsx
Labels: breaking, bug

#203 fix badge display error
  src/api/ApiHelper.tsx
  src/api/WebsocketHelper.tsx
  src/components/AuctionDetails/AuctionDetails.tsx
  src/components/Flipper/Flipper.tsx
  src/components/Search/Search.css
  src/components/Search/Search.tsx
Labels: breaking, bug
